# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Boris DuÅ¡ek
email: me@dusek.me
description: > # this means to ignore newlines until "baseurl:"
  Accessibility Software Engineer homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dusek.github.io" # the base hostname & protocol for your site
twitter_username: BorisDusek
github_username:  dusek
# Build settings
markdown: kramdown
